[project]
name = "shiftml"
version = "0.0.0"
requires-python = ">=3.9"
authors = [
]

dependencies = [
    "numpy",
    "ase==3.22.1",
    "metatensor[torch]",
    "platformdirs",
    "rascaline-torch@git+https://github.com/luthaf/rascaline@e215461#subdirectory=python/rascaline-torch",
]

readme = "README.md"
license = {text = "BSD-3-Clause"}
description = "Predictions of chemical shieldings using machine learning"


[project.urls]
homepage = "https://github.com/lab-cosmo/ShiftML"
# documentation = "TODO"
repository = "https://github.com/lab-cosmo/ShiftML"



[build-system]
requires = [
    "setuptools >=68",
]
build-backend = "setuptools.build_meta"
