[project]
name = "shiftml"
version = "0.2.0"
requires-python = ">=3.10"
authors = [
]
dependencies = [
    "ase",
    "platformdirs",
    "metatensor-torch >=0.10,<0.11",
    "metatomic-torch >=0.1.17,<0.2",
    "metatomic-ase >=0.1.1,<0.2",
    "vesin",
    "requests",
]

readme = "README.md"
license = {text = "BSD-3-Clause"}
description = "Predictions of chemical shieldings using machine learning"

[project.urls]
homepage = "https://github.com/lab-cosmo/ShiftML"
# documentation = "TODO"
repository = "https://github.com/lab-cosmo/ShiftML"



[tool.isort]
# keep `isort` and `black` from fighting over multi-line imports
profile = "black"


[build-system]
requires = [
    "setuptools >=68",
]
build-backend = "setuptools.build_meta"
